config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :enderecos
  resources :municipes

  root 'welcome#index'
  
  get 'municipes/:id/detalhe_endereco', to: 'municipes#detalhe_endereco', as: 'detalhe_endereco'

  
  # For details on the DSL (Domain Specific Language) available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/endereco.rb
class Endereco < ApplicationRecord
    belongs_to :municipe
end

app/models/municipe.rb
class Municipe < ApplicationRecord
    has_one :endereco
    
    accepts_nested_attributes_for :endereco, allow_destroy: true

    has_one_attached :photo

    validates_inclusion_of :birthdate, in: Date.new(1900, 1, 1)..Date.today, message: "A Data de Nascimento deve ser anterior ou igual a data atual"
    
    validates :cns, length: { is: 15 }, numericality: true, presence: true
    validates :cpf, length: { is: 11 }, numericality: true, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_endereco, only: %i[ show edit update destroy ]
  

  # GET /enderecos or /enderecos.json
  def index
    @enderecos = Endereco.all
  end

  # GET /enderecos/1 or /enderecos/1.json
  def show
  end

  # GET /enderecos/new
  def new
    @endereco = Endereco.new(municipe_id: params[:municipe_id])
  end

  # GET /enderecos/1/edit
  def edit
  end

  # POST /enderecos or /enderecos.json
  def create
    @endereco = Endereco.new(endereco_params)

    respond_to do |format|
      if @endereco.save
        format.html { redirect_to endereco_url(@endereco), notice: "Endereco was successfully created." }
        format.json { render :show, status: :created, location: @endereco }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enderecos/1 or /enderecos/1.json
  def update
    respond_to do |format|
      if @endereco.update(endereco_params)
        format.html { redirect_to endereco_url(@endereco), notice: "Endereco was successfully updated." }
        format.json { render :show, status: :ok, location: @endereco }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enderecos/1 or /enderecos/1.json
  def destroy
    @endereco.destroy

    respond_to do |format|
      format.html { redirect_to enderecos_url, notice: "Endereco was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco = Endereco.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def endereco_params
      params.require(:endereco).permit(:cep, :rua, :numero, :complemento, :bairro, :cidade, :uf, :ibge, :municipe_id)
    end
end

app/controllers/municipes_controller.rb
class MunicipesController < ApplicationController
  before_action :set_municipe, only: %i[ show edit update destroy detalhe_endereco ]

  def detalhe_endereco
    @endereco = @municipe.endereco

    render 'municipes/detalhe_endereco'
  end

  # GET /municipes or /municipes.json
  def index
    @municipes = Municipe.all
  end

  # GET /municipes/1 or /municipes/1.json
  def show
  end

  # GET /municipes/new
  def new
    @municipe = Municipe.new
  end

  # GET /municipes/1/edit
  def edit
  end

  # POST /municipes or /municipes.json
  def create
    @municipe = Municipe.new(municipe_params)

    respond_to do |format|
      if @municipe.save
        format.html { redirect_to municipe_url(@municipe), notice: "Municipe foi criado com sucesso." }
        format.json { render :show, status: :created, location: @municipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipes/1 or /municipes/1.json
  def update
    respond_to do |format|
      if @municipe.update(municipe_params)
        format.html { redirect_to municipe_url(@municipe), notice: "Municipe foi editado com sucesso." }
        format.json { render :show, status: :ok, location: @municipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipes/1 or /municipes/1.json
  def destroy
    @municipe.destroy

    respond_to do |format|
      format.html { redirect_to municipes_url, notice: "Municipe foi deletado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipe
      @municipe = Municipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def municipe_params
      params.require(:municipe).permit(:fullname, :cpf, :cns, :email, :birthdate, :phone, :photo, :status, endereco_attributes: [:rua, :complemento, :numero, :bairro, :cidade, :uf, :cep, :ibge])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/municipes_helper.rb
module MunicipesHelper
    def active_or_inactive(municipe_status)
        if municipe_status == true
            "Ativo"
        else
            "Inativo"
        end
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/enderecos/_form.html.erb
<%= stylesheet_link_tag "register_address", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "autocep", media: "all", "data-turbolinks-track" => true%>

<%= form_with(model: endereco, local: true) do |form| %>
  <% if endereco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(endereco.errors.count, "error") %> prohibited this endereco from being saved:</h2>

      <ul>
      <% endereco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cep  %>
    <%= form.text_field :cep, id:"cep", value:"", size:"20", maxlength:"9",
    onblur:"pesquisacep(this.value);" %>
  </div>

  <div class="field">
    <%= form.label :rua %>
    <%= form.text_field :rua, id:"rua" %>
  </div>

  <div class="field">
    <%= form.label :numero %>
    <%= form.text_field :numero, id: "numero" %>
  </div>

  <div class="field">
    <%= form.label :complemento %>
    <%= form.text_field :complemento, id: "complemento" %>
  </div>

  <div class="field">
    <%= form.label :bairro%>
    <%= form.text_field :bairro, id: "bairro" %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade, id: "cidade" %>
  </div>

  <div class="field">
    <%= form.label :uf %>
    <%= form.text_field :uf, id:"uf" %>
  </div>

  <div class="field">
    <%= form.label :ibge %>
    <%= form.text_field :ibge, id: "ibge" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enderecos/_form2.html.erb
<%= stylesheet_link_tag "register", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "autocep", media: "all", "data-turbolinks-track" => true%>



<%= form_with(model: endereco, local: true) do |form| %>
  <%= form.hidden_field :municipe_id %>
  
  <% if endereco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(endereco.errors.count, "error") %> prohibited this endereco from being saved:</h2>

      <ul>
      <% endereco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <section class="table1">
    <div class="row">
    <section class="col-100">
      <%= form.label :cep, id: :label  %>
      <%= form.text_field :cep, id:"cep", value:"", size:"20", maxlength:"9",
      onblur:"pesquisacep(this.value);" %>
    </section>
    </div>

  <div class="firstrow">
    <section class="col-50">
      <%= form.label :rua, id: :label %>
      <%= form.text_field :rua, id:"rua" %>
    </section>
    

    <section class="col-50">
      <%= form.label :numero, id: :label %>
      <%= form.text_field :numero, id:"numero" %>
    </section>
  </div>

  <div class="secondrow">
    <section class="col-50">
      <%= form.label :complemento, id: :label %>
      <%= form.text_field :complemento, id:"complemento" %>
    </section>


    <section class="col-50">
      <%= form.label :bairro, id: :label %>
      <%= form.text_field :bairro, id:"bairro" %>
    </section>
  </div>

  <div class="thirdrow">
    <section class="col-50">
      <%= form.label :cidade, id: :label %>
      <%= form.text_field :cidade, id:"cidade" %>
    </section>


    <section class="col-50">
      <%= form.label :uf, id: :label %>
      <%= form.text_field :uf, id:"uf" %>
    </section>


    <section class="col-50">
      <%= form.label :ibge, id: :label %>
      <%= form.text_field :ibge, id:"ibge" %>
    </section>
  </div>

    <div class="actions">
      <%= form.submit "Cadastrar", id: :btnaction %>
      <%= link_to 'Voltar', :back, id: :btnaction %>
    </div>

  </section>
<% end %>

app/views/enderecos/edit.html.erb
<%= render 'form', endereco: @endereco %>

app/views/enderecos/index.html.erb
 <!DOCTYPE html>
 <html>
    <head>
    <%= stylesheet_link_tag "tablestyle", media: "all", "data-turbolinks-track" => true %>
    </head>


    <body>
    <section class="table1">
        <table>
          <div class="btnsdiv">
      <%= link_to 'Voltar', welcome_index_path, class: "btn new" %>
      </div>

          <thead class="thead1">
          <h1>Endereços</h1>
            <tr>
              <th scope="col">CEP</th>
              <th scope="col">Rua</th>
              <th scope="col">Numero</th>
              <th scope="col">Complemento</th>
              <th scope="col">Bairro</th>
              <th scope="col">Cidade</th>
              <th scope="col">UF</th>
              <th scope="col">IBGE</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
              <% @enderecos.each do |endereco| %>
            <tr>
              <td scope="row"><%= endereco.cep %></td>
            
              <td scope="row"><%= endereco.rua %></td>
            
              <td scope="row"><%= endereco.numero %></td>
            
              <td scope="row"><%= endereco.complemento %></td>
            
              <td scope="row"><%= endereco.bairro %></td>
            
              <td scope="row"><%= endereco.cidade %></td>
                   
              <td scope="row"><%= endereco.uf %></td>

              <td scope="row"><%= endereco.ibge %></td>
            
              <td><%= link_to 'Mostrar', endereco, id: :buttons %></td>

              <td><%= link_to 'Editar', edit_endereco_path(endereco), id: :buttons %></td>

            </tr>
            <% end %>
          </tbody>
        </table>

      
      </section>
    </body>
</html>

app/views/enderecos/new.html.erb
<%= render 'form2', endereco: @endereco %>

app/views/enderecos/show.html.erb
 <!DOCTYPE html>
 <html>
    <head>
    <%= stylesheet_link_tag "tablestyle", media: "all", "data-turbolinks-track" => true %>
    </head>

    <body>
      <section class="table1">
        <table>
          <thead class="thead1">
            <tr>
              <th scope="col">CEP</th>
              <th scope="col">Rua</th>
              <th scope="col">Número</th>
              <th scope="col">Complemento</th>
              <th scope="col">Bairro</th>
              <th scope="col">Cidade</th>
              <th scope="col">UF</th>
              <th scope="col">IBGE</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <tr>
              <td scope="row"><%= @endereco.cep %></td>
              <td scope="row"><%= @endereco.rua %></td>
              <td scope="row"><%= @endereco.numero %></td>
              <td scope="row"><%= @endereco.complemento %></td>
              <td scope="row"><%= @endereco.bairro %></td>
              <td scope="row"><%= @endereco.cidade %></td>
              <td scope="row"><%= @endereco.uf %></td>
              <td scope="row"><%= @endereco.ibge %></td>
            </tr>
          </tbody>
        </table>

      <div class="btnsdiv">

        <%= link_to 'Voltar', enderecos_path, id: :back1 %>
        <%= link_to 'Editar', edit_endereco_path(@endereco), id: :edit1 %>

      </div>
  </section>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleControl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script>
    </script>
  
  </body>
</html>

app/views/municipes/_form.html.erb
<%= stylesheet_link_tag "register", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "autocep", media: "all", "data-turbolinks-track" => true%>

<%= form_with(model: municipe, local: true) do |form| %>
  <% if municipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(municipe.errors.count, "error") %> prohibited this municipe from being saved:</h2>

      <ul>
      <% municipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <section class="table1">
  <div class="row">
    <section class="col-100">
      <%= form.label "Nome Completo", id: :label %>
      <%= form.text_field :fullname, required: :true, placeholder: "Digite seu nome completo", id: :fullnametxt %>
    </section>
  </div>

  <div class="firstrow">
    <section class="col-50">
    <%= form.label "CPF", id: :label %>
    <%= form.text_field :cpf, required: :true, placeholder: "Digite seu CPF", id: :textfield %>
    </section>

    <section class="col-50">
    <%= form.label "CNS", id: :label %>
    <%= form.text_field :cns, required: :true, placeholder: "Digite seu CNS", id: :textfield %>
    </section>
  </div>

  <div class="secondrow">
  <section class="col-50">
    <%= form.label "Endereço de Email", id: :label %>
    <%= form.text_field :email, required: :true, placeholder: "Digite seu Email", id: :textfield %>
  </section>

  <section class="col-50">
    <%= form.label "Telefone", id: :label %>
    <%= form.text_field :phone, required: :true, placeholder: "Digite seu celular", id: :textfield %>
  </section>
  </div>

  <div class="thirdrow">
  <section class="col-50">
    <%= form.label "Data de Nascimento", id: :label %>
    <%= form.date_select :birthdate, start_year: 1900, end_year: Date.today.year, required: true %>

    </section>

  <section class="col-50">
    <%= form.label "Foto", id: :label %>
    <%= form.file_field :photo, id: :filefield %>
  </section>

  <section class="col-50">
    <%= form.label :status, 'Status', id: :label %>
    <%= form.select :status, [['Ativo', true], ['Inativo', false]], required: :true, include_blank: 'Selecione'%>   
  </section>
  </div>
  
  <div class="actions">
    <%= form.submit "Criar cadastro", id: :btnaction %>
    <%= link_to 'Voltar', municipes_path, id: :btnaction %>
  </div>
</section>
<% end %>

app/views/municipes/detalhe_endereco.html.erb
<!DOCTYPE html>
 <html>
    <head>
    <%= stylesheet_link_tag "address", media: "all", "data-turbolinks-track" => true %>
    </head>

     <% if @endereco.present? %>

    <body>
             <section class="table1">
              <table>
                <thead class="thead1"> 

              <h1>
                Endereço de <%= @municipe.fullname %>
              </h1>

            <tr>
              <th scope="col">Rua</th>
              <th scope="col">CEP</th>
              <th scope="col">Numero</th>
              <th scope="col">Complemento</th>
              <th scope="col">Bairro</th>
              <th scope="col">IBGE</th>
              <th scope="col">UF</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <tr>
              <td scope="row"><%= @endereco.rua %></td>
            
              <td scope="row"><%= @endereco.cep %></td>
            
              <td scope="row"><%= @endereco.numero %></td>
            
              <td scope="row"><%= @endereco.complemento %></td>
            
              <td scope="row"><%= @endereco.bairro %></td>
            
              <td scope="row"><%= @endereco.ibge %></td>

              <td scope="row"><%= @endereco.uf %></td>
            </tr>
          </tbody>
        </table>

      <div class="btnsdiv">

        <%= link_to 'Voltar', municipes_path, id: :back1 %>
        <%= link_to 'Editar', edit_endereco_path(@endereco), id: :edit1 %>
      </div>
      </section>

      <% else %>
        <div class="error-msg">
          <p>O munícipe ainda não possui um endereço cadastrado.</p>

            <div class="btnsdiv">
              <%= link_to 'Voltar', municipes_path, id: :edit1 %>
              <%= link_to 'Cadastrar',  new_endereco_path(municipe_id: @municipe.id), id: :edit1 %>
            </div>
        </div>
      <% end %>

    </body>
    </html>
    
  

app/views/municipes/edit.html.erb
<%= render 'form', municipe: @municipe %>

app/views/municipes/index.html.erb
 <!DOCTYPE html>
 <html>
    <head>
    <%= stylesheet_link_tag "tablestyle", media: "all", "data-turbolinks-track" => true %>
    </head>

    <body>
    
    <section class="table1">
    <section class="teste">
    <div class="btnsdiv">
      <%= link_to 'Voltar', welcome_index_path, class: "btn new" %>
      <%= link_to 'Novo Municipe', new_municipe_path, class: "btn new2" %>
      </div>
        </section>

        <table>
          <thead class="thead1">
          <h1>Munícipes</h1>
            <tr>
              <th scope="col">Nome Completo</th>
              <th scope="col">CPF</th>
              <th scope="col">CNS</th>
              <th scope="col">Email</th>
              <th scope="col">Data de Nascimento</th>
              <th scope="col">Telefone</th>
              <th scope="col">Status</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
              <% @municipes.each do |municipe| %>
            <tr>
              <td scope="row"><%= municipe.fullname %></td>
            
              <td scope="row"><%= municipe.cpf %></td>
            
              <td scope="row"><%= municipe.cns %></td>
            
              <td scope="row"><%= municipe.email %></td>
            
              <td scope="row"><%= municipe.birthdate %></td>
            
              <td scope="row"><%= municipe.phone %></td>
                   
              <td scope="row"><%= active_or_inactive(municipe.status) %></td>
            
              <td><%= link_to 'Mostrar', municipe, id: :buttons %></td>

              <td><%= link_to 'Editar', edit_municipe_path(municipe), id: :buttons %></td>
             
            </tr>
            <% end %>
          </tbody>
        </table>

      
      </section>
    </body>
</html>

app/views/municipes/new.html.erb
<%= render 'form', municipe: @municipe %>

app/views/municipes/show.html.erb
 <!DOCTYPE html>
 <html>
    <head>
    <%= stylesheet_link_tag "tablestyle", media: "all", "data-turbolinks-track" => true %>
    </head>


<body>
  <section class="table1">
    <table>
      <thead class="thead1"> 

        <div>
        <%= image_tag(@municipe.photo, size: "250x150") if @municipe.photo.attached? %>
        </div>
        
        <h1>
          <strong><%= @municipe.fullname %></strong>
        </h1>
        
        <tr>
          <th scope="col">CPF</th>
          <th scope="col">CNS</th>
          <th scope="col">E-mail</th>
          <th scope="col">Data de Nascimento</th>
          <th scope="col">Número de Telefone</th>
          <th scope="col">Status</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td scope="row"><%= @municipe.cpf %></td>
          <td scope="row"><%= @municipe.cns %></td>
          <td scope="row"><%= @municipe.email %></td>
          <td scope="row"><%= @municipe.birthdate %></td>
          <td scope="row"><%= @municipe.phone %></td>
          <td scope="row"><%= active_or_inactive(@municipe.status) %></td>

        </tr>
      </tbody>
    </table>

    <div class="btnsdiv">

      <%= link_to 'Voltar', municipes_path, id: :back1 %>
      <%= link_to 'Editar', edit_municipe_path(@municipe), id: :edit1 %>
      <%= link_to 'Mostrar Endereco', detalhe_endereco_path(@municipe), id: :edit1%>
    </div>
  </section>
</body>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag "style", media: "all", "data-turbolinks-track" => true %>
    <nav class="logo">
        <h1>
          <span class="jab">People</span><span class="tv">CONTROL</span
          ><span class="fist">  &#x1F3E5;</span>
        </h1>
    
      <ul>
          <li class="nav-item">
            <%= link_to 'Munícipes', municipes_path %>
          </li>
          <li class="nav-item">
            <%= link_to 'Endereços', enderecos_path %>
          </li>
      </ul>
    </nav>

        <div class="hamburger" id="hamburger">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </div>
  </head>

<body>
  <section class="firstintro">
      <div class="intro-text">
        <h1>
          <span class="hear"> Sistema para cadastro de </span> <br />
          <span class="connecting"> Munícipes e Endereços!</span>
        </h1>

        <p>
          Desenvolvido em Ruby on Rails! 
        </p>
        <%= link_to 'Cadastro de Munícipes', municipes_path, class: "btn red" %>
        <%= link_to 'Endereços Cadastrados', enderecos_path, class: "btn blue" %>
      </div>
      
      <div id="videopreview">
      <%= video_tag "saudevideo.m4a", width: 560, height: 315, controls: true, id: :videoplay %>
      </div>
        <div class="stand-1"></div>
        <div class="stand-2"></div>
    </section>

    

      <script>

      let videopreview = document.querySelector("video");
        let previewTimeout = null;
        let videoPausedAt = null;

        function startPreview() {
          videopreview.muted = true;
          videopreview.playbackRate = 0.5;
          videopreview.play();
        }

        function stopPreview() {
          videoPausedAt = videopreview.currentTime;
          videopreview.pause();
        }

        videopreview.addEventListener("mouseenter", () => {
          if (videoPausedAt === null) {
            startPreview();
          } else {
            videopreview.currentTime = videoPausedAt;
            videoPausedAt = null;
            videopreview.play();
          }
        });

        videopreview.addEventListener("mouseleave", () => {
          stopPreview();
        });
    </script>
  </body>
</html>